apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:latest
          ports:
            - containerPort: 8181
          args:
            - "run"
            - "--server"
            - "/policies/"
          volumeMounts:
            - name: policies
              mountPath: /policies/
      volumes:
        - name: policies
          configMap:

